export type ContentBlock =
  | { type: 'p'; content: string }
  | { type: 'h2'; content: string }
  | { type: 'h3'; content: string }
  | { type: 'ul'; items: string[] }
  | { type: 'callout'; content: string };

export interface BlogPost {
  slug: string;
  category: string;
  title: string;
  excerpt: string;
  image: string;
  readTime: string;
  date: string;
  author: string;
  description: string;
  keywords: string[];
  content: ContentBlock[];
}

export const blogPosts: BlogPost[] = [
  {
    slug: 'fascitis-plantar-guia-recuperacion',
    category: 'Podología Avanzada',
    title: 'Fascitis plantar: Guía completa de recuperación y prevención',
    excerpt: 'Entender la inflamación de la fascia plantar es el primer paso para caminar sin dolor. Exploramos desde el diagnóstico ecográfico hasta las terapias de ondas de choque.',
    image: 'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?q=80&w=2070&auto=format&fit=crop',
    readTime: '8 min',
    date: '15 Mar 2024',
    author: 'Equipo Podofisio Clinic',
    description: 'Guía completa sobre fascitis plantar: síntomas, diagnóstico ecográfico, tratamiento con EPI/EPTE e Indiba, y prevención. Especialistas en Terrassa.',
    keywords: ['fascitis plantar', 'dolor talón', 'fascitis plantar tratamiento', 'fascitis plantar Terrassa', 'podólogo Terrassa'],
    content: [
      { type: 'p', content: 'La fascitis plantar es la causa más frecuente de dolor de talón y representa el 15% de todas las consultas de podología. Si te duele el pie especialmente al levantarte por la mañana o tras un período de reposo, probablemente estés ante esta patología. La buena noticia es que tiene tratamiento eficaz y tiene solución.' },
      { type: 'h2', content: '¿Qué es la fascitis plantar?' },
      { type: 'p', content: 'La fascia plantar es una banda gruesa de tejido conectivo que recorre la planta del pie desde el talón hasta la base de los dedos. Su función es sostener el arco plantar y actuar como amortiguador durante la marcha y el deporte. Cuando esta estructura se somete a tensiones repetidas sin suficiente tiempo de recuperación, desarrolla microrroturas que desencadenan un proceso inflamatorio conocido como fascitis plantar.' },
      { type: 'p', content: 'Afecta principalmente a personas entre 40 y 60 años, aunque es también muy prevalente en corredores, deportistas y personas que pasan muchas horas de pie. En Terrassa y el Vallès Occidental atendemos decenas de casos cada mes, muchos de ellos cronificados por un diagnóstico tardío.' },
      { type: 'h2', content: 'Síntomas: cómo reconocerla' },
      { type: 'p', content: 'El signo más característico es el dolor agudo en la zona interna del talón, especialmente intenso al dar los primeros pasos por la mañana —el llamado "dolor de los primeros pasos"—. Este dolor suele mejorar tras varios minutos caminando pero reaparece con la actividad prolongada o al estar mucho tiempo de pie.' },
      { type: 'ul', items: [
        'Dolor punzante en la planta del pie al levantarte',
        'Rigidez matutina en el arco plantar',
        'Molestia que aumenta al subir escaleras o ponerse de puntillas',
        'Sensación de quemazón o tensión bajo el pie',
        'Dolor que empeora al final del día tras mucha actividad',
      ]},
      { type: 'h2', content: 'Diagnóstico: el papel de la ecografía' },
      { type: 'p', content: 'En Podofisio Clinic diagnosticamos la fascitis plantar mediante ecografía musculoesquelética de alta resolución. Esta prueba permite visualizar en tiempo real el grosor y la integridad de la fascia: un grosor superior a 4 mm en la inserción calcánea es indicativo de fascitis. La ecografía también nos permite descartar otras patologías como espolón calcáneo, bursitis o rotura parcial, y guiar con precisión los tratamientos invasivos.' },
      { type: 'callout', content: 'Un diagnóstico precoz es clave. Una fascitis tratada en fase aguda se resuelve en 6-8 semanas. Si se cronifica, el proceso puede extenderse a 6-12 meses.' },
      { type: 'h2', content: 'Causas y factores de riesgo' },
      { type: 'p', content: 'La fascitis plantar es multifactorial. Los factores más frecuentes que encontramos en consulta son:' },
      { type: 'ul', items: [
        'Biomecánica alterada: pie plano, pie cavo o exceso de pronación',
        'Sobrecarga de entrenamiento en corredores (incremento súbito de kilómetros)',
        'Calzado inadecuado, sin amortiguación o de suela completamente plana',
        'Acortamiento del tríceps sural (gemelos y sóleo tensos)',
        'Trabajo con muchas horas de pie sobre superficies duras',
        'Sobrepeso que incrementa la carga sobre la fascia',
      ]},
      { type: 'h2', content: 'Tratamiento en Podofisio Clinic' },
      { type: 'p', content: 'Utilizamos [ecografía clínica de alta resolución](/servicios/ecografia-clinica) para confirmar el diagnóstico y guiar con precisión el tratamiento. En casos crónicos, la [EPI/EPTE guiada](/servicios/epi-epte-guiada) elimina el tejido degenerado, mientras que la [Radiofrecuencia Indiba](/servicios/radiofrecuencia-indiba) acelera la reparación tisular. Para la corrección biomecánica de base, prescribimos [plantillas 3D personalizadas](/servicios/plantillas-3d-elite).' },
      { type: 'p', content: 'Nuestro abordaje es progresivo y se adapta a la fase de cada caso. No existe un protocolo único: personalizamos el tratamiento según los hallazgos ecográficos, la actividad del paciente y su respuesta clínica.' },
      { type: 'h3', content: 'Fase aguda (0-4 semanas)' },
      { type: 'ul', items: [
        'Fisioterapia manual: masaje transverso profundo y estiramientos asistidos',
        'Radiofrecuencia Indiba para reducir la inflamación y activar la regeneración tisular',
        'Vendaje funcional de descarga plantar',
        'Pautas de actividad modificada y higiene postural',
      ]},
      { type: 'h3', content: 'Fase subaguda y crónica' },
      { type: 'ul', items: [
        'EPI/EPTE guiada por ecografía: electrólisis percutánea que elimina el tejido desvitalizado y estimula la curación real',
        'Plantillas ortopédicas 3D personalizadas para redistribuir las cargas y proteger la inserción calcánea',
        'Programa de ejercicios excéntricos y control motor del pie',
        'Revisión biomecánica completa para corregir la causa de origen',
      ]},
      { type: 'h2', content: 'Prevención: cómo evitar las recaídas' },
      { type: 'p', content: 'Una vez resuelta la fase aguda, la prevención es tan importante como el tratamiento. Las recaídas son frecuentes cuando no se corrigen los factores causales.' },
      { type: 'ul', items: [
        'Realiza estiramientos de la fascia plantar y el tríceps sural cada mañana antes de levantarte',
        'Usa calzado con buena amortiguación y soporte del arco en todo momento',
        'Evita el calzado plano o sin sujeción (chanclas, bailarinas) en períodos largos',
        'Incrementa la carga de entrenamiento de forma progresiva, nunca más de un 10% por semana',
        'Mantén un peso corporal saludable para reducir la carga sobre el pie',
      ]},
      { type: 'callout', content: '¿Llevas más de 2 semanas con dolor en el talón? No esperes a que se cronifique. En Podofisio Clinic en Terrassa te ofrecemos diagnóstico ecográfico el mismo día de la consulta.' },
    ],
  },
  {
    slug: 'tendon-aquiles-tendinopatias',
    category: 'Fisioterapia Deportiva',
    title: 'Tendón de Aquiles: Abordaje clínico en tendinopatías',
    excerpt: 'Analizamos los protocolos de carga progresiva y la importancia del control motor en la rehabilitación de la zona posterior del tobillo.',
    image: 'https://images.unsplash.com/photo-1519823551278-64ac92734fb1?q=80&w=2070&auto=format&fit=crop',
    readTime: '6 min',
    date: '10 Mar 2024',
    author: 'Equipo Podofisio Clinic',
    description: 'Tratamiento de la tendinopatía de Aquiles con fisioterapia invasiva EPI/EPTE en Terrassa. Protocolos de carga excéntrica y control motor para la recuperación completa.',
    keywords: ['tendinopatía aquiles', 'tendón de Aquiles tratamiento', 'fisioterapia Terrassa', 'dolor tendón Aquiles', 'EPI EPTE Terrassa'],
    content: [
      { type: 'p', content: 'El tendón de Aquiles es el más potente del cuerpo humano y también uno de los más propensos a sufrir degeneración por sobrecarga. La tendinopatía aquílea es una patología extremadamente frecuente en corredores, deportistas de equipo y personas con alteraciones biomecánicas del pie, y su abordaje requiere precisión, paciencia y un protocolo bien estructurado.' },
      { type: 'h2', content: '¿Qué es una tendinopatía de Aquiles?' },
      { type: 'p', content: 'A diferencia de lo que se pensaba hace décadas, la tendinopatía aquílea no es principalmente un proceso inflamatorio sino un proceso degenerativo del tejido colágeno. Las fibras de colágeno del tendón pierden su organización paralela, aparece tejido desorganizado y vasos sanguíneos aberrantes, y la capacidad de carga del tendón se ve comprometida. Por eso los antiinflamatorios convencionales tienen un efecto limitado en los casos crónicos.' },
      { type: 'h2', content: 'Tipos y localización' },
      { type: 'ul', items: [
        'Tendinopatía de la porción media (2-6 cm sobre la inserción calcánea): la más frecuente, relacionada con sobrecarga',
        'Tendinopatía insercional (en el punto de unión al calcáneo): más compleja, asociada a espolón de Haglund',
        'Rotura parcial: degeneración avanzada con pérdida de continuidad de algunas fibras',
      ]},
      { type: 'h2', content: 'Síntomas y evolución' },
      { type: 'p', content: 'La tendinopatía de Aquiles suele comenzar con un dolor matutino leve que mejora con el calentamiento. Con el tiempo, si no se trata, el dolor aparece durante el ejercicio y finalmente también en reposo, condicionando seriamente la actividad deportiva y cotidiana.' },
      { type: 'ul', items: [
        'Dolor y rigidez en la zona posterior del tobillo al iniciar la marcha',
        'Engrosamiento palpable del tendón',
        'Dolor que mejora con el calentamiento pero reaparece al enfriar',
        'Crepitación o sensación de crujido al movilizar el tobillo',
        'En casos avanzados: dolor constante que impide correr o incluso caminar',
      ]},
      { type: 'callout', content: 'La tendinopatía de Aquiles raramente se resuelve sola. Sin tratamiento, el riesgo de rotura completa aumenta significativamente, especialmente en deportistas mayores de 40 años.' },
      { type: 'h2', content: 'Diagnóstico ecográfico' },
      { type: 'p', content: 'En Podofisio Clinic utilizamos ecografía de alta resolución para clasificar la gravedad de la tendinopatía, identificar la presencia de neovascularización (vasos aberrantes asociados al dolor crónico), detectar roturas parciales y planificar el tratamiento invasivo con precisión milimétrica.' },
      { type: 'h2', content: 'Tratamiento: el protocolo EPI/EPTE' },
      { type: 'p', content: 'La [Electrólisis Percutánea Intratisular (EPI/EPTE)](/servicios/epi-epte-guiada) guiada por [ecografía](/servicios/ecografia-clinica) es actualmente el tratamiento de referencia para las tendinopatías crónicas. Consiste en la aplicación de una microcorriente galvánica a través de una aguja de acupuntura guiada por imagen directamente sobre el tejido degenerado. La reacción electroquímica elimina el tejido patológico y activa los mecanismos naturales de reparación colágena.' },
      { type: 'h3', content: 'Protocolo de tratamiento en Podofisio Clinic' },
      { type: 'ul', items: [
        'Fase 1 (semanas 1-3): EPI/EPTE para eliminar el tejido degenerado, ejercicios isométricos de carga',
        'Fase 2 (semanas 4-8): ejercicios excéntricos progresivos (protocolo Alfredson modificado), Indiba para potenciar la regeneración',
        'Fase 3 (semanas 9-16): carga funcional progresiva, readaptación deportiva, corrección biomecánica',
        'Fase de mantenimiento: control periódico, plantillas si hay alteración biomecánica subyacente',
      ]},
      { type: 'p', content: 'Completamos la recuperación con [Radiofrecuencia Indiba](/servicios/radiofrecuencia-indiba) para potenciar la regeneración tisular, y en caso de alteración biomecánica subyacente prescribimos [plantillas 3D personalizadas](/servicios/plantillas-3d-elite) tras el [estudio biomecánico](/servicios/biomecanica-digital).' },
      { type: 'h2', content: 'La importancia del control motor y la biomecánica' },
      { type: 'p', content: 'En la mayoría de los casos de tendinopatía aquílea existe una alteración biomecánica subyacente que actúa como factor perpetuador: exceso de pronación, acortamiento del tríceps sural, debilidad de la cadena posterior o patrón de carrera ineficiente. Sin corregir estos factores, las recaídas son prácticamente inevitables.' },
      { type: 'p', content: 'Por eso integramos el estudio biomecánico de la pisada y el análisis del patrón de carrera en el protocolo de recuperación, adaptando las plantillas y las pautas de entrenamiento a cada caso.' },
      { type: 'callout', content: '¿Llevas semanas con dolor en el talón o en la zona posterior del tobillo? El tendón de Aquiles responde mejor a la intervención temprana. Solicita tu evaluación ecográfica en Podofisio Clinic Terrassa.' },
    ],
  },
  {
    slug: 'metatarsalgia-presion-patologia',
    category: 'Anatomía Funcional',
    title: 'Metatarsalgia: Cuando la presión se convierte en patología',
    excerpt: 'El dolor en la almohadilla plantar puede ocultar diversas patologías. Descubre cómo las plantillas personalizadas corrigen la biomecánica.',
    image: 'https://images.unsplash.com/photo-1579154235602-3c20fa4f597e?q=80&w=2070&auto=format&fit=crop',
    readTime: '5 min',
    date: '05 Mar 2024',
    author: 'Equipo Podofisio Clinic',
    description: 'Qué es la metatarsalgia, sus causas biomecánicas y cómo las plantillas 3D personalizadas en Terrassa alivian el dolor en el antepié.',
    keywords: ['metatarsalgia', 'dolor antepié', 'plantillas ortopédicas Terrassa', 'metatarsalgia tratamiento', 'podólogo Terrassa'],
    content: [
      { type: 'p', content: 'El dolor en la zona delantera de la planta del pie —el antepié— es una queja extremadamente frecuente en consulta. Bajo el término "metatarsalgia" se agrupa un conjunto de patologías que tienen en común la sobrecarga de las cabezas de los metatarsianos, los cinco huesos largos que forman el puente del pie. Identificar correctamente la causa es fundamental para elegir el tratamiento adecuado.' },
      { type: 'h2', content: '¿Qué es la metatarsalgia?' },
      { type: 'p', content: 'Los metatarsianos actúan como amortiguadores durante la fase de propulsión de la marcha. Cuando la distribución de presiones es desigual —por alteraciones biomecánicas, calzado inadecuado o deformidades del pie—, alguna o varias cabezas metatarsales reciben una carga excesiva que provoca inflamación, dolor y, con el tiempo, cambios estructurales en el tejido.' },
      { type: 'h2', content: 'Tipos y causas más frecuentes' },
      { type: 'h3', content: 'Metatarsalgia mecánica' },
      { type: 'p', content: 'La más común. Causada por una distribución anormal de presiones en el antepié: pie cavo con antepié equino, insuficiencia del primer radio, dedos en garra o martillo que transfieren la carga hacia las cabezas centrales, y calzado de tacón que concentra el peso en el antepié.' },
      { type: 'h3', content: 'Neuroma de Morton' },
      { type: 'p', content: 'Engrosamiento del nervio digital plantar, habitualmente entre el 3.º y 4.º metatarsianos. Produce un dolor urente, irradiado hacia los dedos, con sensación de quemazón o de caminar sobre una piedra. Diagnóstico confirmado por ecografía.' },
      { type: 'h3', content: 'Bursitis intermetatarsal' },
      { type: 'p', content: 'Inflamación de las pequeñas bolsas serosas entre los metatarsianos. Frecuente en deportistas y personas con pie plano transverso.' },
      { type: 'ul', items: [
        'Pie cavo o pie plano que altera la distribución de carga',
        'Calzado de tacón alto o puntera estrecha',
        'Dedos en martillo o garra que sobrecargan el antepié',
        'Artritis reumatoide o gota (metatarsalgia secundaria)',
        'Actividades de alto impacto sin calzado adecuado',
      ]},
      { type: 'h2', content: 'Diagnóstico: ecografía y baropodometría' },
      { type: 'p', content: 'En Podofisio Clinic combinamos dos herramientas diagnósticas. La [ecografía de alta resolución](/servicios/ecografia-clinica) permite visualizar el neuroma de Morton, las bursitis y las alteraciones del tejido blando periarticular. La [plataforma baropodométrica del estudio biomecánico](/servicios/biomecanica-digital) registra en tiempo real la distribución de presiones plantares durante la marcha.' },
      { type: 'callout', content: 'La baropodometría es imprescindible para diseñar plantillas realmente efectivas. Sin conocer el mapa de presiones exacto de cada pie, cualquier plantilla es una estimación.' },
      { type: 'h2', content: 'Tratamiento con plantillas 3D personalizadas' },
      { type: 'p', content: 'Las plantillas ortopédicas personalizadas son el tratamiento conservador más eficaz para la metatarsalgia mecánica. En Podofisio Clinic las fabricamos mediante tecnología de impresión aditiva 3D a partir del escaneo tridimensional del pie y los datos baropodométricos de cada paciente.' },
      { type: 'ul', items: [
        'Barra metatarsal retroalimentada: desplaza las presiones hacia atrás, aliviando las cabezas metatarsales',
        'Corrección del arco plantar: en pie cavo o plano que altera la carga del antepié',
        'Materiales de alta amortiguación en zonas de hiperpresión',
        'Diseño fino para calzado de uso deportivo o de calle',
      ]},
      { type: 'h2', content: 'Tratamiento del neuroma de Morton' },
      { type: 'p', content: 'Cuando existe un neuroma confirmado por ecografía, el tratamiento combina la plantilla descompresiva con infiltraciones ecoguiadas o, en casos refractarios, con la esclerosis percutánea del nervio. La cirugía queda reservada para los casos que no responden a ninguna medida conservadora.' },
      { type: 'callout', content: '¿Sientes una quemazón o "piedra" bajo el pie al caminar? Podría ser un neuroma de Morton. En Podofisio Clinic Terrassa lo diagnosticamos con ecografía en la primera visita.' },
    ],
  },
  {
    slug: 'radiofrecuencia-indiba-fisioterapia',
    category: 'Tecnología Médica',
    title: 'Beneficios de la Radiofrecuencia Indiba en Fisioterapia',
    excerpt: 'Cómo la hipertermia controlada acelera la regeneración celular y reduce los tiempos de recuperación en lesiones musculares.',
    image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?q=80&w=2070&auto=format&fit=crop',
    readTime: '7 min',
    date: '01 Mar 2024',
    author: 'Equipo Podofisio Clinic',
    description: 'Cómo funciona la radiofrecuencia Indiba en fisioterapia: beneficios, indicaciones y por qué es una de las terapias más eficaces para lesiones musculoesqueléticas en Terrassa.',
    keywords: ['radiofrecuencia Indiba Terrassa', 'Indiba fisioterapia', 'diatermia Terrassa', 'fisioterapia Terrassa', 'recuperación lesiones Terrassa'],
    content: [
      { type: 'p', content: 'La radiofrecuencia Indiba es una de las tecnologías más avanzadas disponibles en fisioterapia y una de las que mejores resultados clínicos ofrece en el tratamiento de lesiones musculoesqueléticas. En Podofisio Clinic la utilizamos a diario para acelerar la recuperación de nuestros pacientes en Terrassa, y los resultados hablan por sí mismos: tiempos de recuperación significativamente reducidos y resolución de dolores crónicos que no respondían a tratamientos convencionales.' },
      { type: 'h2', content: '¿Qué es la radiofrecuencia Indiba?' },
      { type: 'p', content: 'Indiba es un sistema de diatermia (calentamiento profundo del tejido) que utiliza una corriente eléctrica de radiofrecuencia a 448 kHz para transferir energía al interior del cuerpo. Esta frecuencia específica no produce sensación dolorosa y penetra en profundidad, alcanzando estructuras que las terapias superficiales no pueden tratar.' },
      { type: 'p', content: 'Existen dos modalidades de aplicación que se combinan según el objetivo terapéutico: el modo capacitivo (CAP), que actúa sobre tejidos blandos superficiales como músculos y fascias, y el modo resistivo (RES), que penetra más profundamente para tratar articulaciones, tendones, ligamentos y hueso.' },
      { type: 'h2', content: '¿Cómo funciona a nivel celular?' },
      { type: 'p', content: 'El efecto principal de la radiofrecuencia Indiba es la hipertermia controlada: eleva la temperatura del tejido tratado entre 1 y 3 °C por encima de la temperatura basal. Este incremento térmico, perfectamente tolerado, desencadena una cascada de efectos biológicos beneficiosos:' },
      { type: 'ul', items: [
        'Aumento del flujo sanguíneo y linfático: mejora el aporte de nutrientes y oxígeno al tejido lesionado',
        'Activación de fibroblastos: células responsables de sintetizar nuevo colágeno y reparar el tejido conectivo',
        'Efecto analgésico: reducción de la sensibilización de los nociceptores y disminución del dolor local',
        'Reducción del edema: favorece el drenaje de los líquidos inflamatorios acumulados',
        'Relajación muscular: disminuye la hipertonía muscular y los puntos gatillo miofasciales',
      ]},
      { type: 'callout', content: 'La radiofrecuencia Indiba no es calor superficial: es energía que penetra en los tejidos profundos, activando los mecanismos naturales de reparación donde realmente se necesita.' },
      { type: 'h2', content: '¿Para qué lesiones está indicada?' },
      { type: 'p', content: 'En Podofisio Clinic aplicamos Indiba en un amplio espectro de patologías musculoesqueléticas:' },
      { type: 'h3', content: 'Lesiones agudas' },
      { type: 'ul', items: [
        'Esguinces de tobillo y rodilla (a partir de las 48 h post-lesión)',
        'Roturas musculares fibrilares (acorta significativamente el tiempo de recuperación)',
        'Tendinitis y bursitis en fase aguda',
        'Contusiones y hematomas',
      ]},
      { type: 'h3', content: 'Patologías crónicas' },
      { type: 'ul', items: [
        'Fascitis plantar crónica y tendinopatía de Aquiles',
        'Epicondilitis lateral y medial ("codo de tenista")',
        'Síndrome del manguito rotador',
        'Dolor lumbar crónico y ciática',
        'Artrosis de rodilla, cadera y tobillo',
        'Fibromialgia y dolor miofascial difuso',
      ]},
      { type: 'h2', content: '¿Cómo es una sesión de Indiba?' },
      { type: 'p', content: 'La sesión dura entre 20 y 45 minutos según la zona a tratar. El fisioterapeuta aplica un electrodo activo (cabezal de silicona conductora) sobre la zona tratada y un electrodo retorno (placa) en el cuerpo del paciente. La sensación es de un calor agradable y progresivo, sin ningún dolor. La gran mayoría de pacientes refieren mejoría ya en la primera o segunda sesión.' },
      { type: 'h2', content: '¿Cuántas sesiones son necesarias?' },
      { type: 'p', content: 'El número varía según la patología y su cronificación. Como referencia orientativa: lesiones agudas (3-5 sesiones), tendinopatías crónicas (8-12 sesiones combinadas con otros tratamientos), artrosis y patologías degenerativas (ciclos de mantenimiento periódicos). En Podofisio Clinic nunca pautamos sesiones sin una evaluación previa y un objetivo clínico claro.' },
      { type: 'p', content: 'En Podofisio Clinic Terrassa integramos la radiofrecuencia Indiba con otros tratamientos como la [EPI/EPTE guiada por ecografía](/servicios/epi-epte-guiada) y el [estudio biomecánico digital](/servicios/biomecanica-digital) para ofrecer un abordaje completo de tu lesión.' },
      { type: 'callout', content: 'La radiofrecuencia Indiba obtiene los mejores resultados cuando se combina con fisioterapia activa y ejercicio terapéutico. Descubre también nuestra [EPI/EPTE guiada por ecografía](/servicios/epi-epte-guiada) para las tendinopatías crónicas que no responden a terapias conservadoras.' },
    ],
  },
  {
    slug: 'calzado-deportivo-tipo-pisada',
    category: 'Prevención',
    title: 'Calzado Deportivo: Cómo elegir según tu tipo de pisada',
    excerpt: 'No todas las zapatillas son para todos los pies. Te damos las claves para elegir el calzado que mejor protege tu salud biomecánica.',
    image: 'https://images.unsplash.com/photo-1562157873-818bc0726f68?q=80&w=2070&auto=format&fit=crop',
    readTime: '10 min',
    date: '25 Feb 2024',
    author: 'Equipo Podofisio Clinic',
    description: 'Guía completa para elegir zapatillas deportivas según tu tipo de pisada: pronadora, supinadora o neutra. Consejos de nuestros podólogos en Terrassa.',
    keywords: ['calzado deportivo pisada', 'zapatillas pronación Terrassa', 'tipo de pisada', 'estudio pisada Terrassa', 'podólogo Terrassa'],
    content: [
      { type: 'p', content: 'Una de las preguntas más habituales en la consulta de podología es: "¿Qué zapatillas me recomiendas?". La respuesta honesta es que no existe una zapatilla perfecta para todos. La elección del calzado deportivo debe basarse en tu tipo de pisada, tu morfología del pie, el tipo de actividad y la superficie donde la realizas. Elegir mal puede ser el origen de lesiones que van desde la fascitis plantar hasta la tendinopatía de Aquiles.' },
      { type: 'h2', content: 'Los tres tipos de pisada' },
      { type: 'h3', content: 'Pisada pronadora' },
      { type: 'p', content: 'La pronación es el movimiento natural de rotación interna del pie al contactar con el suelo. Es un mecanismo de amortiguación necesario. El problema aparece cuando esta rotación es excesiva (hiperpronación): el pie se hunde hacia dentro más de lo normal, lo que sobrecargan la fascia plantar, el tendón tibial posterior y la rodilla. Suele asociarse a pie plano o valgo.' },
      { type: 'h3', content: 'Pisada supinadora' },
      { type: 'p', content: 'La supinación es el movimiento contrario: el pie rueda hacia fuera. Una supinación excesiva reduce la capacidad de amortiguación del pie y concentra las cargas en el borde externo, aumentando el riesgo de esguinces de tobillo y estrés en el quinto metatarsiano. Suele asociarse a pie cavo.' },
      { type: 'h3', content: 'Pisada neutra' },
      { type: 'p', content: 'La pisada neutra implica un grado óptimo de pronación durante la marcha. El impacto se distribuye de forma equilibrada por toda la planta del pie. No significa que no puedas tener lesiones, pero el riesgo biomecánico es menor.' },
      { type: 'callout', content: 'El test del mojado (humedecer la planta del pie y pisar un papel) es una orientación muy rudimentaria. El único método fiable para determinar tu tipo de pisada es un estudio biomecánico con plataforma de presiones, como los que realizamos en Podofisio Clinic Terrassa.' },
      { type: 'h2', content: 'Qué buscar en una zapatilla según tu pisada' },
      { type: 'h3', content: 'Si pisas con pronación excesiva' },
      { type: 'ul', items: [
        'Zapatillas de control de movimiento o estabilidad (Motion Control / Stability)',
        'Entresuela con densidad dual: más dura en la zona interna (mediopié) para frenar la pronación',
        'Horma recta o semirrecta',
        'Evitar zapatillas minimalistas o con mucho drop negativo',
      ]},
      { type: 'h3', content: 'Si pisas con supinación' },
      { type: 'ul', items: [
        'Zapatillas neutras con alta amortiguación, especialmente en el talón y el antepié',
        'Entresuela blanda y flexible que favorezca la pronación natural',
        'Horma curva que acompañe la mecánica del pie cavo',
        'Buen refuerzo lateral del tobillo para prevenir esguinces',
      ]},
      { type: 'h3', content: 'Si tienes pisada neutra' },
      { type: 'ul', items: [
        'Zapatillas neutras con buena amortiguación general',
        'Libertad para elegir según preferencia de amortiguación y confort',
        'Priorizar el ajuste correcto (longitud, anchura) sobre las características técnicas',
      ]},
      { type: 'h2', content: 'Más allá del tipo de pisada: otros factores clave' },
      { type: 'ul', items: [
        'Anchura del pie: muchas lesiones vienen de zapatillas demasiado estrechas en el antepié',
        'El drop (diferencia de altura talón-punta): un drop alto (>10mm) descarga el tendón de Aquiles; uno bajo (<4mm) lo exige más',
        'El peso de la zapatilla: más peso = más fatiga en carreras largas',
        'La superficie: no uses las mismas zapatillas para asfalto que para trail',
        'La vida útil: una zapatilla de running pierde sus propiedades de amortiguación entre los 500 y 800 km',
      ]},
      { type: 'h2', content: 'Cuándo las zapatillas no son suficientes' },
      { type: 'p', content: 'Si tienes una alteración biomecánica significativa —pie plano severo, valgo de retropié, exceso de pronación, pie cavo rígido—, las zapatillas estabilizadoras pueden ayudar pero raramente son suficientes. En estos casos, las plantillas ortopédicas personalizadas, adaptadas exactamente a tu pie y a tu zapatilla, ofrecen una corrección mucho más precisa y eficaz.' },
      { type: 'callout', content: '¿No sabes cómo pisas? En Podofisio Clinic realizamos el [estudio biomecánico completo de la pisada](/servicios/biomecanica-digital) con plataforma de presiones. En una única visita sabrás exactamente qué calzado y qué [plantillas personalizadas](/servicios/plantillas-3d-elite) necesitas.' },
    ],
  },
  {
    slug: 'esguince-tobillo-grado-ii',
    category: 'Casos Clínicos',
    title: 'Recuperación de Esguince de Tobillo Grado II',
    excerpt: 'Estudio de caso sobre el abordaje integral mediante terapia manual, ejercicio terapéutico y neuromodulación.',
    image: 'https://images.unsplash.com/photo-1531844251246-9a1bfaae09fc?q=80&w=2070&auto=format&fit=crop',
    readTime: '12 min',
    date: '20 Feb 2024',
    author: 'Equipo Podofisio Clinic',
    description: 'Protocolo completo de recuperación de esguince de tobillo grado II en Terrassa: fisioterapia manual, EPI, Indiba, propiocepción y readaptación deportiva.',
    keywords: ['esguince tobillo tratamiento', 'fisioterapia esguince Terrassa', 'esguince grado II recuperación', 'fisioterapeuta Terrassa', 'tobillo esguince'],
    content: [
      { type: 'p', content: 'El esguince de tobillo es la lesión musculoesquelética más frecuente en la práctica deportiva y una de las más infratratadas. La falsa creencia de que "un esguince solo necesita reposo e hielo" ha generado miles de tobillos con inestabilidad crónica, re-esguinces repetidos y dolor persistente que podrían haberse evitado con un tratamiento adecuado desde el principio.' },
      { type: 'h2', content: 'Clasificación: entendiendo el grado II' },
      { type: 'p', content: 'Los esguinces de tobillo se clasifican en tres grados según la severidad de la lesión ligamentosa:' },
      { type: 'ul', items: [
        'Grado I: distensión del ligamento sin rotura de fibras. Dolor leve, sin inestabilidad, recuperación en 1-2 semanas',
        'Grado II: rotura parcial del ligamento (habitualmente el ligamento peroneoastragalino anterior, LPAA). Dolor moderado-severo, edema importante, posible equimosis e inestabilidad funcional. Recuperación: 3-8 semanas',
        'Grado III: rotura completa del ligamento. Inestabilidad marcada, dolor intenso, edema severo. Puede requerir valoración quirúrgica',
      ]},
      { type: 'callout', content: 'Un esguince grado II no bien tratado genera hasta un 70% de riesgo de re-esguince en los siguientes 12 meses. El tratamiento rehabilitador completo —no solo el reposo— es la clave para evitar la inestabilidad crónica.' },
      { type: 'h2', content: 'Fase aguda (0-72 horas): PRICE y más' },
      { type: 'p', content: 'El manejo inmediato del esguince sigue el protocolo PRICE (Protection, Rest, Ice, Compression, Elevation), pero en Podofisio Clinic lo complementamos desde las primeras horas para acortar la fase inflamatoria sin eliminarla —la inflamación inicial es necesaria para la reparación—.' },
      { type: 'ul', items: [
        'Vendaje funcional de inmovilización parcial que protege el tobillo sin impedir completamente la movilidad',
        'Crioterapia intermitente (20 min cada 2-3 horas) en las primeras 48 h',
        'Elevación del miembro para reducir el edema',
        'Inicio precoz de ejercicios isométricos y movilización activa suave (cuando el dolor lo permita)',
        '[Radiofrecuencia Indiba](/servicios/radiofrecuencia-indiba) desde las 48-72 h para acelerar la reabsorción del hematoma',
      ]},
      { type: 'h2', content: 'Fase subaguda (3-21 días): restaurar la movilidad y la fuerza' },
      { type: 'p', content: 'Una vez controlada la fase aguda, el objetivo es recuperar el rango de movimiento completo del tobillo y comenzar el trabajo de fortalecimiento de los músculos estabilizadores (peroneos, tibial anterior y posterior).' },
      { type: 'ul', items: [
        'Fisioterapia manual: movilizaciones articulares del tobillo y pie para recuperar el rango de movimiento',
        'Masoterapia y drenaje linfático manual para reducir el edema residual',
        'Ejercicios de fortalecimiento muscular: isométricos, isotónicos y trabajo excéntrico de peroneos',
        'Inicio de ejercicios propioceptivos en superficie estable',
        '[EPI/EPTE](/servicios/epi-epte-guiada) sobre el tejido ligamentoso lesionado para estimular la reparación colágena',
      ]},
      { type: 'h2', content: 'Fase funcional (3-8 semanas): propiocepción y readaptación' },
      { type: 'p', content: 'La propiocepción —la capacidad del sistema nervioso para detectar la posición del tobillo en el espacio— es la clave para evitar recaídas. Un tobillo que ha sufrido un esguince pierde parte de sus receptores propioceptivos, lo que explica el alto índice de re-esguinces si no se reeducan.' },
      { type: 'ul', items: [
        'Progresión de ejercicios propioceptivos: superficie inestable, ojos cerrados, single-leg balance',
        'Ejercicios pliométricos y de cambio de dirección para la readaptación deportiva',
        'Entrenamiento funcional específico del deporte del paciente',
        'Vendaje neuromuscular o funcional en los primeros retornos al deporte',
      ]},
      { type: 'h2', content: 'Alta clínica: criterios de retorno al deporte' },
      { type: 'p', content: 'En Podofisio Clinic no damos el alta hasta que el paciente cumple criterios objetivos de recuperación, no solo subjetivos (ausencia de dolor). Evaluamos:' },
      { type: 'ul', items: [
        'Rango de movimiento completo del tobillo sin dolor',
        'Fuerza de los peroneos ≥90% respecto al tobillo sano (dinamometría)',
        'Equilibrio monopodal ≥90% respecto al lado sano (plataforma de equilibrio)',
        'Capacidad para realizar saltos, cambios de dirección y gesto deportivo sin miedo ni compensaciones',
      ]},
      { type: 'callout', content: '¿Has sufrido un esguince de tobillo? No esperes a que "se cure solo". Cuanto antes comiences la rehabilitación, menor será el tiempo de recuperación y el riesgo de inestabilidad crónica. Llámanos o escríbenos por WhatsApp.' },
    ],
  },
];

export function getBlogPost(slug: string): BlogPost | undefined {
  return blogPosts.find((post) => post.slug === slug);
}
